image: docker

cache:
  paths:
    - .m2/repository

variables:

  REGISTRY_IMAGE: $GROUP_REGISTRY_DOMAIN/jtdigi/services/docker/product-catalogue-service                               
  MAVEN_OPTS: -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
 
  
stages: [mavnage, dockage]


# Vlastní maven sestavení
mejvnob:
  stage: mavnage
  image: openjdk:11
  script:
    - echo VERZE=$(git describe --match v\* --first-parent) >> build.env
    - ./mvnw clean package --settings settings.xml
  artifacts:
    paths:
      - target/*.jar
      - build.env

# Docker sestavení a publikace
dokrob:
  stage: dockage
  image: docker
  before_script:
    - docker login -u $GROUP_REGISTRY_USER -p $GROUP_REGISTRY_DEPLOY_TOKEN $GROUP_REGISTRY_DOMAIN
  script:
    - . build.env
    - VYSLEDNY_TAG1=$REGISTRY_IMAGE/${CI_COMMIT_REF_SLUG}:$CI_PIPELINE_ID
    - VYSLEDNY_TAG2=$REGISTRY_IMAGE:$VERZE
    
    - docker build -t $VYSLEDNY_TAG1 .
    - docker tag $VYSLEDNY_TAG1 $VYSLEDNY_TAG2
    

    - docker push $VYSLEDNY_TAG1
    - docker push $VYSLEDNY_TAG2
  dependencies: 
    - mejvnob
    
  
