server:
  port: 8443
spring:
  jackson:
    date-format: com.asseco.ce.jtsr_digi.product_catalogue.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
