spring:
  datasource:
    url: jdbc:oracle:thin:@//jtsr-ivp-db.assecosk.local:1521/JTDIGI_D
    driver-class-name: oracle.jdbc.OracleDriver
    username: DATREP247_PUBLIC
    password: DATREP247
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
