server:
  port: 8080
  servlet:
    context-path: /productcatalogue
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: dev
  jackson:
    date-format: com.asseco.ce.jtsrdigi.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

management:
  endpoint:
    health:
      show-details: never    # possible values:  never, always, when-authorized, http://localhost:8080/productcatalogue/actuator/health
  endpoints:
    web:
      exposure:
#        include: health,info,prometheus,metrics,threaddump # http://localhost:8080/productcatalogue/actuator/prometheus, http://localhost:8080/productcatalogue/actuator/info
        include: "*"

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

slf4jfilter:
  request-header:
    - X-Correlation-ID
    - X-Request-ID
  request-param:
    - systemId
    - requestTimestamp

logging:
  level:
    root: WARN
    com.asseco.ce.jtsrdigi: INFO
  pattern:
    console: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%X{X-Correlation-ID} %X{X-Request-ID}] %c - %msg%n"
