package com.asseco.ce.jtsr_digi.product_catalogue.domain;
// Generated Dec 15, 2020, 11:05:00 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ErTPeriodCatalougeId generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Embeddable
public class ErTPeriodCatalougeId  implements java.io.Serializable {


   

    @Column(name="PERIOD_CODE", nullable=false, precision=3, scale=0)
  private short periodCode;
   

    @Column(name="TEXT", nullable=false, length=20)
  private String text;
   

    @Column(name="SYSREF", nullable=false, precision=15, scale=0)
  private long sysref;


}


