package com.asseco.ce.jtsr_digi.product_catalogue.domain;
// Generated Dec 15, 2020, 11:05:00 AM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PcTProductCatalogueTs generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="PC_T_PRODUCT_CATALOGUE_TS"
)
public class PcTProductCatalogueTs  implements java.io.Serializable {


        @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productid", column=@Column(name="PRODUCTID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="dateFrom", column=@Column(name="DATE_FROM", nullable=false, length=7) ), 
        @AttributeOverride(name="attrId", column=@Column(name="ATTR_ID", nullable=false, precision=30, scale=0) ) } )
  private PcTProductCatalogueTsId id;
   
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCTID", nullable=false, insertable=false, updatable=false)
  private PcTProduct pcTProduct;
   
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ATTR_ID", nullable=false, insertable=false, updatable=false)
  private EnumTProdcatAttr enumTProdcatAttr;
   
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CURRENCY_ID")
  private EnumTCurrency enumTCurrency;
   
    
    @Column(name="VALUE", length=50)
  private String value;
   
    @Temporal(TemporalType.DATE)
    @Column(name="DATE_TO", nullable=false, length=7)
  private Date dateTo;


}


