package com.asseco.ce.jtsr_digi.product_catalogue.domain;
// Generated Dec 15, 2020, 11:05:00 AM by Hibernate Tools 6.0.0.Alpha2


import java.math.BigInteger;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PcTProductCatalogue generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="PC_T_PRODUCT_CATALOGUE"
)
public class PcTProductCatalogue  implements java.io.Serializable {


        @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productid", column=@Column(name="PRODUCTID", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="attrId", column=@Column(name="ATTR_ID", nullable=false, precision=30, scale=0) ), 
        @AttributeOverride(name="langCode", column=@Column(name="LANG_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="orderValue", column=@Column(name="ORDER_VALUE", nullable=false, precision=22, scale=0) ), 
        @AttributeOverride(name="validFrom", column=@Column(name="VALID_FROM", nullable=false, length=7) ) } )
  private PcTProductCatalogueId id;
   
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LANG_CODE", nullable=false, insertable=false, updatable=false)
  private CfgTLang cfgTLang;
   
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ATTR_ID", nullable=false, insertable=false, updatable=false)
  private EnumTProdcatAttr enumTProdcatAttr;
   
    @Temporal(TemporalType.DATE)
    @Column(name="D_ATTR_VALUE", length=7)
  private Date DAttrValue;
   
    
    @Column(name="E_ATTR_VALUE", length=80)
  private String EAttrValue;
   
    
    @Column(name="C_ATTR_VALUE", length=2000)
  private String CAttrValue;
   
    
    @Column(name="N_ATTR_VALUE", precision=22, scale=0)
  private BigInteger NAttrValue;
   
    @Temporal(TemporalType.DATE)
    @Column(name="VALID_TO", length=7)
  private Date validTo;


}


